const {chromium} = require(process.env.TASK_NODE_MODULES + '/playwright');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const out = path.join(root, 'tests/artifacts/ojt_v1');
fs.mkdirSync(out, {recursive:true});
const data = JSON.parse(fs.readFileSync(path.join(root, 'data/tutorial.json'), 'utf8'));
const spb = 60/data.bpm;
const target = (4+data.rounds[0].length+2+data.rounds[0].beats[0].beat)*spb;
(async()=>{
 const errors=[];
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:1280,height:720}});
 page.on('pageerror', e=>errors.push(String(e)));
 page.on('console', m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto('http://127.0.0.1:8766/');
 await page.waitForFunction(()=>window.TaskHeavenStatus?.state==='title');
 await page.mouse.click(220,489);
 await page.waitForFunction(()=>window.TaskHeavenStatus?.state==='help');
 await page.mouse.click(335,535);
 await page.waitForFunction(()=>window.TaskHeavenStatus?.ojt===true);
 await page.screenshot({path:path.join(out,'help_ojt_on.png')});
 await page.mouse.click(290,597);
 await page.waitForFunction(()=>window.TaskHeavenStatus?.state==='playing');
 await page.waitForFunction(t=>TaskAudio.clock()>=t,target-1.6*spb,{polling:'raf'});
 await page.screenshot({path:path.join(out,'countdown.png')});
 await page.waitForFunction(t=>TaskAudio.clock()>=t,target-.8*spb,{polling:'raf'});
 await page.screenshot({path:path.join(out,'ojt_cue.png')});
 const cueStatus=await page.evaluate(()=>TaskHeavenStatus);
 await page.waitForFunction(t=>TaskAudio.clock()>=t,target,{polling:'raf'});
 await page.keyboard.press(String(data.rounds[0].beats[0].channel));
 await page.waitForFunction(()=>window.TaskHeavenStatus?.counts.PERFECT>=1);
 await page.mouse.click(1207,48);
 await page.waitForFunction(()=>window.TaskHeavenStatus?.state==='paused');
 await page.mouse.click(640,446);
 await page.waitForFunction(()=>window.TaskHeavenStatus?.ojt===false);
 const pausedOff=await page.evaluate(()=>TaskHeavenStatus.ojt);
 await page.mouse.click(640,446);
 await page.waitForFunction(()=>window.TaskHeavenStatus?.ojt===true);
 const pausedOn=await page.evaluate(()=>TaskHeavenStatus.ojt);
 await page.screenshot({path:path.join(out,'pause_ojt_on.png')});
 const report={cueStatus,pausedOff,pausedOn,perfect:await page.evaluate(()=>TaskHeavenStatus.counts.PERFECT),errors};
 fs.writeFileSync(path.join(out,'ojt_browser.json'),JSON.stringify(report,null,2));
 await browser.close();
 if(pausedOff||!pausedOn||errors.length)throw Error(JSON.stringify(report));
 console.log(JSON.stringify(report));
})().catch(e=>{console.error(e);process.exit(1);});
